clone:
  depth: 1

pipelines:
  default:
    - step:
        image: ktomk/pipelines:busybox
        name: pipeline features and introspection
        script:
          - echo "test" || true
          - lib/pipelines/environment.sh

  custom:
    lint-php-5.3:
      - step: &lint-php53
          image: php:5.3
          script:
            - lib/pipelines/lint.sh
    unit-tests-php-5.3:
      - step:
          # has no zip: tomsowerby/php-5.3:cli
          image: cespi/php-5.3:cli-latest
          script:
            - command -v composer || lib/pipelines/composer-install.sh
            - composer show -i phpunit/phpunit 2>/dev/null| head -n 4 | sed -n -e 's/versions.*\* //p'
            - >
              composer show -i --name-only phpunit/phpunit 2>/dev/null| head -n 4 | sed -n -e 's/versions.*\* //p'
              | grep -q '^4.' || { composer remove --dev friendsofphp/php-cs-fixer phpunit/phpunit;
                composer require --no-suggest --dev phpunit/phpunit ^4; }
            - vendor/bin/phpunit # --testsuite unit,integration by default w/ phpunit 4.8.36
          services:
            - docker
    lint-php-7.4:
      - step: &lint-php74
          <<: *lint-php53
          image: php:7.4
    lint-php:
      - step: *lint-php53
      - step: *lint-php74
    unit-tests: # run phpunit suite
      - step:
          image: php:7.0
          script:
            - vendor/bin/phpunit --testsuite unit,integration
          services:
            - docker
    artifact-tests: # run phpunit suite w/ artifact
      - step:
          image: php:7.0
          script:
            - vendor/bin/phpunit
          artifacts:
            - build/html/testdox.html
    docker:
      - step:
          image: ktomk/pipelines:busybox
          name: docker-in-docker
          script:
            - docker version --format {{.Client.Version}}
            - docker version --format {{.Server.Version}}
            - docker ps
            - docker inspect pipelines-1.docker-in-docker.custom-docker.pipelines | head -n 8
          services:
            - docker
    docker-install:
      - step:
          image: php:7.0
          name: docker-in-docker w/ install script
          script:
            - lib/pipelines/docker-client-install.sh
            - docker version
            - docker version --format {{.Client.Version}}
            - docker version --format {{.Server.Version}}
            - bin/pipelines --deploy mount --keep
    docker-phar:
      - step:
          image: php:7.0
          name: default pipeline inside pipelines pipeline
          script:
            - docker version
            - docker version --format {{.Client.Version}}
            - docker version --format {{.Server.Version}}
            - build/pipelines.phar --no-keep
          services:
            - docker
    docker-phar-install:
      - step:
          image: php:7.0
          name: default pipeline inside pipelines pipeline (extra docker client install)
          script:
            - lib/pipelines/docker-client-install.sh
            - docker version
            - docker version --format {{.Client.Version}}
            - docker version --format {{.Server.Version}}
            - build/pipelines.phar --no-keep
    recursion:
      - step:
          image: php:7.0
          script:
            - docker version --format {{.Client.Version}}
            - docker version --format {{.Server.Version}}
            - docker cp --help
            - bin/pipelines --pipeline custom/recursion/middle
          services:
            - docker
    recursion/middle:
      - step:
          image: php:7.0
          script:
            - php --version
      - step:
          image: php:7.0
          script:
            - docker version --format {{.Client.Version}}
            - docker version --format {{.Server.Version}}
            - bin/pipelines --pipeline custom/recursion --dry-run # must fail
          services:
            - docker
    private/docker-hub:
      - step:
          image:
            name: vicampotk/private
            username: $DOCKER_ID_USER
            password: $DOCKER_ID_PASSWORD
            email: $DOCKER_ID_EMAIL
          script:
            - lib/pipelines/environment.sh
            - env
    printenv:
      - step:
          image: ktomk/pipelines:busybox
          name: print environemnt variables
          script:
            - printenv
